@echo off
rem Copyright (c) 2026:
rem vatofichor - Sebastian Mass     [>_<]
rem and Assisted By Gemini Antigravity /^|\
rem Licensed under the MIT License. See LICENSE in the project root.

echo ========================================================
echo md2web Reader - Windows Environment Installer
echo ========================================================
echo.

set "SCRIPT_DIR=%~dp0"
set "ZIP_PATH=%SCRIPT_DIR%lib\php.zip"
set "EXTRACT_DIR=%SCRIPT_DIR%lib\php"
set "RUNNER_SRC=%SCRIPT_DIR%lib\windows_run-server.bat"
set "RUNNER_DEST=%SCRIPT_DIR%windows_run-server.bat"

rem 1. Verify packaged PHP zip archive exists in lib
if not exist "%ZIP_PATH%" (
    echo [ERROR] Bundled PHP package not found at:
    echo         "%ZIP_PATH%"
    echo.
    echo Please verify that lib\php.zip is present in the project directory.
    echo.
    echo Press any key to exit...
    pause
    exit /b 1
)

echo [1/3] Found packaged PHP archive: lib\php.zip

rem 2. Unpack PHP zip into lib\php
if exist "%EXTRACT_DIR%\php.exe" (
    echo [2/3] Packaged PHP environment already extracted at lib\php\. Skipping unpack.
) else (
    echo [2/3] Extracting packaged PHP archive into lib\php\ ...
    powershell -NoProfile -ExecutionPolicy Bypass -Command "Expand-Archive -Path '%ZIP_PATH%' -DestinationPath '%EXTRACT_DIR%' -Force"
    if %errorlevel% neq 0 (
        echo.
        echo [ERROR] Failed to extract PHP zip package.
        echo Please ensure PowerShell is available and try again.
        echo.
        echo Press any key to exit...
        pause
        exit /b 1
    )
    echo [OK] Extraction completed successfully.
)

rem 3. Generate server runtime configuration file (lib\server_config.bat)
echo [3/4] Generating server runtime environment configuration...
if exist "%EXTRACT_DIR%\php.exe" goto :GEN_PACKAGED_CONFIG
goto :GEN_SYSTEM_CONFIG

:GEN_PACKAGED_CONFIG
(
    echo rem Generated by windows_install.bat
    echo set "CONFIGURED_PHP_CMD=%%~dp0php\php.exe"
) > "%SCRIPT_DIR%lib\server_config.bat"
echo  - Configured: Packaged PHP runtime (lib\php\php.exe)
goto :DEPLOY_SCRIPTS

:GEN_SYSTEM_CONFIG
(
    echo rem Generated by windows_install.bat
    echo set "CONFIGURED_PHP_CMD=php"
) > "%SCRIPT_DIR%lib\server_config.bat"
echo  - Configured: System PHP CLI (PATH)
goto :DEPLOY_SCRIPTS

:DEPLOY_SCRIPTS
rem 4. Deploy server runner and alias scripts to root
echo [4/4] Deploying server runner and launcher aliases...

if exist "%RUNNER_SRC%" (
    copy /Y "%RUNNER_SRC%" "%RUNNER_DEST%" >nul
    echo  - Deployed: windows_run-server.bat
)

rem Deploy command launchers
(
    echo @echo off
    echo call "%%~dp0windows_run-server.bat" %%*
) > "%SCRIPT_DIR%md2web.bat"
echo  - Deployed: md2web.bat

(
    echo @echo off
    echo call "%%~dp0windows_run-server.bat" %%*
) > "%SCRIPT_DIR%md2reader.bat"
echo  - Deployed: md2reader.bat

(
    echo @echo off
    echo call "%%~dp0dev\admin_scripts\windows_create_desktop_shortcut.bat" %%*
) > "%SCRIPT_DIR%windows_create_shortcut.bat"
echo  - Deployed: windows_create_shortcut.bat

echo [OK] Server scripts deployed successfully.

echo.
echo ========================================================
echo Installation complete! You can start the server by:
echo   - Launching "windows_run-server.bat", "md2web.bat", or "md2reader.bat"
echo   - Optional: Run "dev\admin_scripts\windows_add_to_path.bat" to add
echo     this directory to your Windows User PATH.
echo ========================================================
echo.
echo Press any key to close installer...
pause
